image: alpine
before_script:
  - eval `ssh-agent -s` && ssh-add
  - sh bootstrap.sh
  - bin/buildout -N
  - bin/buildout -N remotes:branch=$CI_COMMIT_REF_NAME
  - bin/develop up --force
stages:
  - test

test_sanbox_true:
  stage: test
  variables:
    SANDBOX_MODE: 'True'
  script:
    - bin/py.test ./openprocurement/tender/openeu/tests/ --cov=openprocurement.tender.openeu


test_sanbox_not_true:
  stage: test
  variables:
    SANDBOX_MODE: ''
  script:
    - bin/py.test ./openprocurement/tender/openeu/tests/ --cov=openprocurement.tender.openeu